import { NextResponse } from 'next/server';
import { connectDB } from '@/lib/mongodb';
import { User } from '@/lib/models/User';
import { FiatCard } from '@/lib/models/FiatCard';

type CardType = 'personal' | 'business';
type Network = 'AMEX' | 'VISA' | 'MASTERCARD' | 'DISCOVER';
type CurrencyType = 'USD' | 'POINTS' | 'MILES';

function buildCards(userId: string) {
  return [
    // ── 1. Chase Sapphire Reserve ─────────────────────────────────────────────
    {
      user_id: userId,
      card_id: 'card_chase_sapphire_reserve_01',
      display_name: 'Chase Sapphire Reserve',
      card_type: 'personal' as CardType,
      network: 'VISA' as Network,
      currency_type: 'POINTS' as CurrencyType,
      current_balance_owed: 0,
      credit_limit: 30000,
      points_balance: 52000,
      credit_token_balance: 0,
      redemption_rate_display: '1 Point = 1.5 cents (Chase Travel)',
      points_value_cents: 150,
      points_program_name: 'Chase Ultimate Rewards',
      card_description: 'The definitive premium travel card. $300 travel credit nearly halves the $550 annual fee. Priority Pass Select lounge access, 3x on all travel and dining, and best-in-class travel protections including trip delay reimbursement.',
      pros: [
        '$300 annual travel credit offsets fee significantly',
        'Priority Pass Select — unlimited lounge visits + 2 guests',
        '3x points on all travel and dining with no category caps',
        '10x points on Chase Travel portal bookings',
        'Best-in-class trip delay, cancellation, and interruption insurance',
        'Primary rental car CDW coverage',
        'Global Entry / TSA PreCheck credit ($100)',
        'Points worth 1.5¢ each toward travel via Chase Travel',
        'Transfer to 14 airline and hotel partners',
      ],
      cons: [
        '$550 annual fee (highest in its tier)',
        'Must spend through Chase Travel to get 10x rate',
        'Authorized user fee of $75 per person',
      ],
      features: [
        '3x on travel and dining worldwide',
        '10x on hotels/cars via Chase Travel, 5x on flights via Chase Travel',
        '1x on all other purchases',
        '$300 annual travel credit (auto-applies to any travel category)',
        'Priority Pass Select — unlimited visits + 2 guests',
        '$60 DoorDash credit + free DashPass membership',
        '$60 Peloton credit per year',
        'Global Entry/TSA PreCheck credit',
        'Trip delay insurance: $500/ticket after 6 hours',
        'Trip cancellation/interruption insurance: up to $10,000/person',
        'Primary rental CDW — declines other cards',
        'Baggage delay insurance: $100/day, 5 days max',
        'Emergency evacuation/transportation coverage',
      ],
      financials: {
        annual_fee: 550,
        foreign_transaction_fee_pct: 0,
        standard_apr: 0.2174,
      },
      rewards_structure: {
        base_multiplier: 1,
        fixed_categories: [
          { category: 'travel', multiplier: 3, cap_amount_usd: null, cap_period: null, current_spend_towards_cap: 0, post_cap_multiplier: 1 },
          { category: 'flights', multiplier: 3, cap_amount_usd: null, cap_period: null, current_spend_towards_cap: 0, post_cap_multiplier: 1 },
          { category: 'hotel', multiplier: 3, cap_amount_usd: null, cap_period: null, current_spend_towards_cap: 0, post_cap_multiplier: 1 },
          { category: 'dining', multiplier: 3, cap_amount_usd: null, cap_period: null, current_spend_towards_cap: 0, post_cap_multiplier: 1 },
          { category: 'rental car', multiplier: 3, cap_amount_usd: null, cap_period: null, current_spend_towards_cap: 0, post_cap_multiplier: 1 },
        ],
      },
      benefits_and_credits: {
        statement_credits: [
          { name: 'Annual Travel Credit', amount_usd: 300, reset_period: 'calendar_year', amount_redeemed: 0, merchant_categories: ['travel', 'flights', 'hotel', 'rental car', 'rideshare'] },
          { name: 'DoorDash Credit', amount_usd: 60, reset_period: 'calendar_year', amount_redeemed: 0, merchant_categories: ['dining', 'delivery'] },
          { name: 'Peloton Credit', amount_usd: 60, reset_period: 'calendar_year', amount_redeemed: 0, merchant_categories: ['fitness'] },
        ],
        portal_bonuses: [
          { portal_name: 'Chase Travel', portal_url: 'https://travel.chase.com', categories: ['flights', 'hotel', 'rental car'], bonus_multiplier: 10, bonus_type: 'multiplier' as const },
        ],
        purchase_protections: {
          extended_warranty: true,
          purchase_protection_days: 120,
          return_protection_days: 90,
          cell_phone_protection: true,
          trip_cancellation: true,
          primary_rental_cdw: true,
        },
        transfer_partners: [
          { program: 'United MileagePlus', ratio: '1:1', cpp_min: 1.20, cpp_max: 2.10 },
          { program: 'Southwest Rapid Rewards', ratio: '1:1', cpp_min: 1.40, cpp_max: 1.70 },
          { program: 'British Airways Avios', ratio: '1:1', cpp_min: 1.40, cpp_max: 2.40 },
          { program: 'Air France/KLM Flying Blue', ratio: '1:1', cpp_min: 1.30, cpp_max: 1.90 },
          { program: 'World of Hyatt', ratio: '1:1', cpp_min: 1.50, cpp_max: 2.30 },
          { program: 'Marriott Bonvoy', ratio: '1:1', cpp_min: 0.70, cpp_max: 1.10 },
          { program: 'Singapore Airlines KrisFlyer', ratio: '1:1', cpp_min: 1.50, cpp_max: 2.20 },
          { program: 'Virgin Atlantic Flying Club', ratio: '1:1', cpp_min: 1.40, cpp_max: 1.90 },
        ],
        airline_perks: [
          'Priority Pass Select — unlimited visits + 2 guests',
          'Global Entry credit ($100)',
          'TSA PreCheck credit ($85)',
          'Trip delay insurance (6hr threshold, $500/ticket)',
          'Trip cancellation/interruption up to $10,000/person',
        ],
        general_perks: [
          'No foreign transaction fees',
          'Lyft Pink membership',
          'Primary rental CDW worldwide',
          'Lost luggage reimbursement up to $3,000',
          'Emergency medical evacuation',
        ],
      },
    },

    // ── 2. Chase Sapphire Preferred ───────────────────────────────────────────
    {
      user_id: userId,
      card_id: 'card_chase_sapphire_preferred_01',
      display_name: 'Chase Sapphire Preferred',
      card_type: 'personal' as CardType,
      network: 'VISA' as Network,
      currency_type: 'POINTS' as CurrencyType,
      current_balance_owed: 0,
      credit_limit: 15000,
      points_balance: 28000,
      credit_token_balance: 0,
      redemption_rate_display: '1 Point = 1.25 cents (Chase Travel)',
      points_value_cents: 125,
      points_program_name: 'Chase Ultimate Rewards',
      card_description: 'The best entry-level travel rewards card. At $95/year you get 3x on dining and online groceries, 2x on all other travel, access to all 14 Chase transfer partners, and solid travel protections.',
      pros: [
        'Low $95 annual fee for the value delivered',
        '3x on dining and online groceries',
        '2x on all travel — no complicated sub-categories',
        'Access to all 14 Ultimate Rewards transfer partners',
        '$50 annual hotel credit via Chase Travel',
        'Trip delay insurance at just $95/year',
        'Primary rental car insurance',
        'Points worth 1.25¢ via Chase Travel portal',
      ],
      cons: [
        'No lounge access at any level',
        'Points worth 0.25¢ less per point than Reserve',
        '3% foreign transaction fee (overcome by no-FTF alternative)',
      ],
      features: [
        '3x on dining, online grocery (excl. Target/Walmart/wholesale)',
        '2x on all travel',
        '1x on everything else',
        '5x on Chase Travel portal (flights), 3x on hotels via portal',
        '$50 annual Chase Travel hotel credit',
        'Points transfer to 14+ airline and hotel partners at 1:1',
        'Trip delay insurance: $500/ticket after 12 hours',
        'Trip cancellation insurance: up to $10,000/person',
        'Primary rental CDW',
        'Baggage delay insurance: $100/day, 5 days',
      ],
      financials: {
        annual_fee: 95,
        foreign_transaction_fee_pct: 0,
        standard_apr: 0.2074,
      },
      rewards_structure: {
        base_multiplier: 1,
        fixed_categories: [
          { category: 'dining', multiplier: 3, cap_amount_usd: null, cap_period: null, current_spend_towards_cap: 0, post_cap_multiplier: 1 },
          { category: 'restaurant', multiplier: 3, cap_amount_usd: null, cap_period: null, current_spend_towards_cap: 0, post_cap_multiplier: 1 },
          { category: 'grocer', multiplier: 3, cap_amount_usd: null, cap_period: null, current_spend_towards_cap: 0, post_cap_multiplier: 1 },
          { category: 'travel', multiplier: 2, cap_amount_usd: null, cap_period: null, current_spend_towards_cap: 0, post_cap_multiplier: 1 },
          { category: 'flights', multiplier: 2, cap_amount_usd: null, cap_period: null, current_spend_towards_cap: 0, post_cap_multiplier: 1 },
          { category: 'hotel', multiplier: 2, cap_amount_usd: null, cap_period: null, current_spend_towards_cap: 0, post_cap_multiplier: 1 },
          { category: 'streaming', multiplier: 3, cap_amount_usd: null, cap_period: null, current_spend_towards_cap: 0, post_cap_multiplier: 1 },
        ],
      },
      benefits_and_credits: {
        statement_credits: [
          { name: 'Chase Travel Hotel Credit', amount_usd: 50, reset_period: 'anniversary_year', amount_redeemed: 0, merchant_categories: ['hotel'] },
        ],
        portal_bonuses: [
          { portal_name: 'Chase Travel', portal_url: 'https://travel.chase.com', categories: ['flights', 'hotel', 'rental car'], bonus_multiplier: 5, bonus_type: 'multiplier' as const },
        ],
        purchase_protections: {
          extended_warranty: true,
          purchase_protection_days: 120,
          return_protection_days: 90,
          cell_phone_protection: false,
          trip_cancellation: true,
          primary_rental_cdw: true,
        },
        transfer_partners: [
          { program: 'United MileagePlus', ratio: '1:1', cpp_min: 1.20, cpp_max: 2.10 },
          { program: 'Southwest Rapid Rewards', ratio: '1:1', cpp_min: 1.40, cpp_max: 1.70 },
          { program: 'British Airways Avios', ratio: '1:1', cpp_min: 1.40, cpp_max: 2.40 },
          { program: 'Air France/KLM Flying Blue', ratio: '1:1', cpp_min: 1.30, cpp_max: 1.90 },
          { program: 'World of Hyatt', ratio: '1:1', cpp_min: 1.50, cpp_max: 2.30 },
          { program: 'Singapore Airlines KrisFlyer', ratio: '1:1', cpp_min: 1.50, cpp_max: 2.20 },
        ],
        airline_perks: ['Trip delay insurance (12hr threshold)', 'Primary rental CDW'],
        general_perks: ['No foreign transaction fees', 'Lyft Pink access'],
      },
    },

    // ── 3. Amex Platinum ──────────────────────────────────────────────────────
    {
      user_id: userId,
      card_id: 'card_amex_platinum_01',
      display_name: 'Amex Platinum',
      card_type: 'personal' as CardType,
      network: 'AMEX' as Network,
      currency_type: 'POINTS' as CurrencyType,
      current_balance_owed: 0,
      credit_limit: 25000,
      points_balance: 75000,
      credit_token_balance: 0,
      redemption_rate_display: '1 MR Point = 1.0–2.0 cents',
      points_value_cents: 150,
      points_program_name: 'Amex Membership Rewards',
      card_description: 'The pinnacle of lifestyle credit cards. $695 annual fee offset by $1,400+ in annual credits. Access to 1,400+ airport lounges worldwide including Centurion Lounges, Delta Sky Clubs, and Priority Pass.',
      pros: [
        'Centurion Lounge access (best food/drink in airport lounges)',
        '$200 annual airline fee credit',
        '$200 annual Uber Cash credit',
        '$200 annual hotel credit via Amex Fine Hotels + Resorts',
        '$155 Walmart+ credit',
        '$100 Saks Fifth Avenue credit per year',
        '$300 Equinox credit',
        '$240 digital entertainment credit',
        'Global Entry/TSA PreCheck credit ($100)',
        '5x on flights booked directly + prepaid hotels via Amex Travel',
        'Transfer to 20+ airline and hotel partners',
      ],
      cons: [
        '$695 annual fee — highest in mainstream market',
        'Credits require active management to redeem',
        'Centurion Lounge overcrowding complaints in peak hours',
        '5x on flights capped at $500k per year',
      ],
      features: [
        '5x Membership Rewards on flights booked directly with airlines',
        '5x on prepaid hotels via Amex Travel',
        '2x on other Amex Travel purchases',
        '1x on all other purchases',
        '$200 Uber Cash credit (monthly $15 + $20 December)',
        '$200 airline fee credit (checked bags, seat upgrades, in-flight)',
        '$200 Fine Hotels + Resorts or Hotel Collection credit',
        '$155 Walmart+ credit (monthly $12.95)',
        '$100 Saks credit ($50 Jan–Jun, $50 Jul–Dec)',
        '$300 Equinox credit',
        '$240 digital entertainment credit ($20/month)',
        'Centurion Lounge + Priority Pass + Delta Sky Club access',
        'CLEAR Plus membership credit ($189)',
        'Global Entry credit ($100)',
      ],
      financials: {
        annual_fee: 695,
        foreign_transaction_fee_pct: 0,
        standard_apr: 0.0,
      },
      rewards_structure: {
        base_multiplier: 1,
        fixed_categories: [
          { category: 'flights', multiplier: 5, cap_amount_usd: 500000, cap_period: 'calendar_year', current_spend_towards_cap: 0, post_cap_multiplier: 1 },
          { category: 'hotel', multiplier: 5, cap_amount_usd: null, cap_period: null, current_spend_towards_cap: 0, post_cap_multiplier: 1 },
          { category: 'travel', multiplier: 2, cap_amount_usd: null, cap_period: null, current_spend_towards_cap: 0, post_cap_multiplier: 1 },
        ],
      },
      benefits_and_credits: {
        statement_credits: [
          { name: 'Uber Cash', amount_usd: 200, reset_period: 'calendar_year', amount_redeemed: 0, merchant_categories: ['rideshare', 'uber eats'] },
          { name: 'Airline Fee Credit', amount_usd: 200, reset_period: 'calendar_year', amount_redeemed: 0, merchant_categories: ['flights', 'airline'] },
          { name: 'Fine Hotels + Resorts', amount_usd: 200, reset_period: 'calendar_year', amount_redeemed: 0, merchant_categories: ['hotel'] },
          { name: 'Saks Fifth Avenue', amount_usd: 100, reset_period: 'calendar_year', amount_redeemed: 0, merchant_categories: ['shopping', 'fashion'] },
          { name: 'Equinox', amount_usd: 300, reset_period: 'calendar_year', amount_redeemed: 0, merchant_categories: ['fitness'] },
          { name: 'Digital Entertainment', amount_usd: 240, reset_period: 'calendar_year', amount_redeemed: 0, merchant_categories: ['streaming', 'entertainment'] },
          { name: 'Walmart+', amount_usd: 155, reset_period: 'calendar_year', amount_redeemed: 0, merchant_categories: ['grocery', 'retail'] },
          { name: 'CLEAR Plus', amount_usd: 189, reset_period: 'calendar_year', amount_redeemed: 0, merchant_categories: ['travel', 'airport'] },
        ],
        portal_bonuses: [
          { portal_name: 'Amex Travel', portal_url: 'https://travel.americanexpress.com', categories: ['flights', 'hotel'], bonus_multiplier: 1.5, bonus_type: 'multiplier' as const },
        ],
        purchase_protections: {
          extended_warranty: true,
          purchase_protection_days: 90,
          return_protection_days: 90,
          cell_phone_protection: false,
          trip_cancellation: true,
          primary_rental_cdw: false,
        },
        transfer_partners: [
          { program: 'Delta SkyMiles', ratio: '1:1', cpp_min: 1.10, cpp_max: 1.80 },
          { program: 'British Airways Avios', ratio: '1:1', cpp_min: 1.40, cpp_max: 2.40 },
          { program: 'Air France/KLM Flying Blue', ratio: '1:1', cpp_min: 1.30, cpp_max: 1.90 },
          { program: 'ANA Mileage Club', ratio: '1:1', cpp_min: 1.60, cpp_max: 2.80 },
          { program: 'Singapore Airlines KrisFlyer', ratio: '1:1', cpp_min: 1.50, cpp_max: 2.20 },
          { program: 'Virgin Atlantic Flying Club', ratio: '1:1', cpp_min: 1.40, cpp_max: 2.00 },
          { program: 'Cathay Pacific Asia Miles', ratio: '1:1', cpp_min: 1.30, cpp_max: 2.10 },
          { program: 'Hilton Honors', ratio: '1:2', cpp_min: 0.40, cpp_max: 0.70 },
          { program: 'Marriott Bonvoy', ratio: '1:1', cpp_min: 0.70, cpp_max: 1.10 },
        ],
        airline_perks: [
          'Centurion Lounge access worldwide',
          'Priority Pass Select — unlimited visits',
          'Delta Sky Club access (when flying Delta)',
          'Escape Lounge access',
          'Global Entry credit ($100)',
          'CLEAR Plus credit ($189)',
        ],
        general_perks: [
          'No foreign transaction fees',
          'Amex Concierge service 24/7',
          'Amex Fine Hotels + Resorts program',
          'International Airline Program (business/first class discounts)',
        ],
      },
    },

    // ── 4. Amex Gold ──────────────────────────────────────────────────────────
    {
      user_id: userId,
      card_id: 'card_amex_gold_01',
      display_name: 'Amex Gold',
      card_type: 'personal' as CardType,
      network: 'AMEX' as Network,
      currency_type: 'POINTS' as CurrencyType,
      current_balance_owed: 0,
      credit_limit: 20000,
      points_balance: 43000,
      credit_token_balance: 0,
      redemption_rate_display: '1 MR Point = 1.0–2.0 cents',
      points_value_cents: 140,
      points_program_name: 'Amex Membership Rewards',
      card_description: 'The undisputed winner for foodies and grocery shoppers. 4x at US supermarkets ($25k cap) and 4x at restaurants worldwide. $120 dining credit and $120 Uber Cash effectively halves the $250 annual fee.',
      pros: [
        '4x points at US supermarkets (up to $25,000/year)',
        '4x points at restaurants worldwide — no caps',
        '3x points on flights booked directly with airlines',
        '$120 dining credit ($10/month at Grubhub, Cheesecake Factory, etc.)',
        '$120 Uber Cash credit ($10/month)',
        '$100 hotel credit via Amex Travel (2-night stay min)',
        'Access to 20+ transfer partners',
        'No foreign transaction fees',
      ],
      cons: [
        '$250 annual fee',
        'Grocery bonus capped at $25,000 per calendar year',
        'No lounge access (Platinum required)',
        'Credits require monthly activation to capture',
      ],
      features: [
        '4x at US supermarkets (up to $25k spend, then 1x)',
        '4x at restaurants worldwide',
        '3x on flights booked directly with airlines or amextravel.com',
        '1x on all other eligible purchases',
        '$120 dining credit ($10/month: Grubhub, Seamless, Cheesecake Factory, Ruth\'s Chris)',
        '$120 Uber Cash credit ($10/month: Uber rides + Uber Eats)',
        '$100 hotel credit on 2-night+ bookings via Amex Travel',
        'Transfer to 20+ airline and hotel partners',
        'Amex Offers personalized merchant discounts',
      ],
      financials: {
        annual_fee: 250,
        foreign_transaction_fee_pct: 0,
        standard_apr: 0.0,
      },
      rewards_structure: {
        base_multiplier: 1,
        fixed_categories: [
          { category: 'grocer', multiplier: 4, cap_amount_usd: 25000, cap_period: 'calendar_year', current_spend_towards_cap: 0, post_cap_multiplier: 1 },
          { category: 'dining', multiplier: 4, cap_amount_usd: null, cap_period: null, current_spend_towards_cap: 0, post_cap_multiplier: 1 },
          { category: 'restaurant', multiplier: 4, cap_amount_usd: null, cap_period: null, current_spend_towards_cap: 0, post_cap_multiplier: 1 },
          { category: 'flights', multiplier: 3, cap_amount_usd: null, cap_period: null, current_spend_towards_cap: 0, post_cap_multiplier: 1 },
        ],
      },
      benefits_and_credits: {
        statement_credits: [
          { name: 'Dining Credit', amount_usd: 120, reset_period: 'calendar_year', amount_redeemed: 0, merchant_categories: ['dining', 'restaurant', 'delivery'] },
          { name: 'Uber Cash', amount_usd: 120, reset_period: 'calendar_year', amount_redeemed: 0, merchant_categories: ['rideshare', 'uber eats'] },
          { name: 'Amex Travel Hotel Credit', amount_usd: 100, reset_period: 'calendar_year', amount_redeemed: 0, merchant_categories: ['hotel'] },
        ],
        portal_bonuses: [
          { portal_name: 'Amex Travel', portal_url: 'https://travel.americanexpress.com', categories: ['hotel'], bonus_multiplier: 1.3, bonus_type: 'multiplier' as const },
        ],
        purchase_protections: {
          extended_warranty: false,
          purchase_protection_days: 90,
          return_protection_days: 0,
          cell_phone_protection: false,
          trip_cancellation: false,
          primary_rental_cdw: false,
        },
        transfer_partners: [
          { program: 'Delta SkyMiles', ratio: '1:1', cpp_min: 1.10, cpp_max: 1.80 },
          { program: 'British Airways Avios', ratio: '1:1', cpp_min: 1.40, cpp_max: 2.40 },
          { program: 'Air France/KLM Flying Blue', ratio: '1:1', cpp_min: 1.30, cpp_max: 1.90 },
          { program: 'Singapore Airlines KrisFlyer', ratio: '1:1', cpp_min: 1.50, cpp_max: 2.20 },
          { program: 'Virgin Atlantic Flying Club', ratio: '1:1', cpp_min: 1.40, cpp_max: 2.00 },
          { program: 'Marriott Bonvoy', ratio: '1:1', cpp_min: 0.70, cpp_max: 1.10 },
          { program: 'Hilton Honors', ratio: '1:2', cpp_min: 0.40, cpp_max: 0.70 },
        ],
        airline_perks: [],
        general_perks: ['No foreign transaction fees', 'Amex Offers discounts'],
      },
    },

    // ── 5. Capital One Venture X ──────────────────────────────────────────────
    {
      user_id: userId,
      card_id: 'card_capital_one_venture_x_01',
      display_name: 'Capital One Venture X',
      card_type: 'personal' as CardType,
      network: 'VISA' as Network,
      currency_type: 'MILES' as CurrencyType,
      current_balance_owed: 0,
      credit_limit: 30000,
      points_balance: 38000,
      credit_token_balance: 0,
      redemption_rate_display: '1 Mile = 1.0–1.5 cents',
      points_value_cents: 125,
      points_program_name: 'Capital One Venture Rewards',
      card_description: 'The best value premium travel card at $395/year. $300 Capital One Travel credit + 10,000 anniversary miles (worth $100) effectively reduces the annual fee to under zero for active travelers.',
      pros: [
        '2x miles on every purchase — no category management',
        '10x on hotels and rental cars via Capital One Travel',
        '5x on flights via Capital One Travel',
        '$300 annual Capital One Travel credit',
        '10,000 bonus miles every account anniversary (~$100 value)',
        'Priority Pass Select — unlimited visits + guests',
        'Capital One Lounge access (LAS, DFW, DEN)',
        'No foreign transaction fees',
        '15+ transfer partners',
      ],
      cons: [
        '$395 annual fee',
        'Capital One transfer partners fewer than Chase/Amex',
        'Authorized user fee of $75',
      ],
      features: [
        '2x miles on all purchases',
        '10x miles on hotels and rental cars via Cap1 Travel',
        '5x miles on flights via Cap1 Travel',
        '$300 Capital One Travel credit (auto-applies)',
        '10,000 anniversary bonus miles',
        'Unlimited Priority Pass Select visits + 2 guests',
        'Capital One Lounge access at select airports',
        '$100 Global Entry or TSA PreCheck credit',
        'Cell phone protection (up to $800)',
        'Extended warranty up to 2 years',
        'Trip delay/cancellation insurance',
        'Primary rental CDW',
        'No foreign transaction fees',
      ],
      financials: {
        annual_fee: 395,
        foreign_transaction_fee_pct: 0,
        standard_apr: 0.1974,
      },
      rewards_structure: {
        base_multiplier: 2,
        fixed_categories: [
          { category: 'hotel', multiplier: 10, cap_amount_usd: null, cap_period: null, current_spend_towards_cap: 0, post_cap_multiplier: 2 },
          { category: 'rental car', multiplier: 10, cap_amount_usd: null, cap_period: null, current_spend_towards_cap: 0, post_cap_multiplier: 2 },
          { category: 'flights', multiplier: 5, cap_amount_usd: null, cap_period: null, current_spend_towards_cap: 0, post_cap_multiplier: 2 },
        ],
      },
      benefits_and_credits: {
        statement_credits: [
          { name: 'Capital One Travel Credit', amount_usd: 300, reset_period: 'calendar_year', amount_redeemed: 0, merchant_categories: ['travel', 'flights', 'hotel', 'rental car'] },
        ],
        portal_bonuses: [
          { portal_name: 'Capital One Travel', portal_url: 'https://travel.capitalone.com', categories: ['flights', 'hotel', 'rental car'], bonus_multiplier: 1.5, bonus_type: 'multiplier' as const },
        ],
        purchase_protections: {
          extended_warranty: true,
          purchase_protection_days: 90,
          return_protection_days: 90,
          cell_phone_protection: true,
          trip_cancellation: true,
          primary_rental_cdw: true,
        },
        transfer_partners: [
          { program: 'Air Canada Aeroplan', ratio: '1:1', cpp_min: 1.40, cpp_max: 2.20 },
          { program: 'Turkish Airlines Miles&Smiles', ratio: '1:1', cpp_min: 1.30, cpp_max: 2.50 },
          { program: 'Avianca LifeMiles', ratio: '1:1', cpp_min: 1.30, cpp_max: 1.80 },
          { program: 'British Airways Avios', ratio: '1:1', cpp_min: 1.40, cpp_max: 2.40 },
          { program: 'Singapore Airlines KrisFlyer', ratio: '1:1', cpp_min: 1.50, cpp_max: 2.20 },
          { program: 'Air France/KLM Flying Blue', ratio: '1:1', cpp_min: 1.30, cpp_max: 1.90 },
          { program: 'Wyndham Rewards', ratio: '1:1', cpp_min: 0.90, cpp_max: 1.40 },
        ],
        airline_perks: ['Priority Pass Select unlimited', 'Capital One Lounge access', 'Global Entry credit'],
        general_perks: ['No foreign transaction fees', 'Cell phone protection', 'Primary rental CDW'],
      },
    },

    // ── 6. Chase Freedom Unlimited ────────────────────────────────────────────
    {
      user_id: userId,
      card_id: 'card_chase_freedom_unlimited_01',
      display_name: 'Chase Freedom Unlimited',
      card_type: 'personal' as CardType,
      network: 'VISA' as Network,
      currency_type: 'POINTS' as CurrencyType,
      current_balance_owed: 0,
      credit_limit: 12000,
      points_balance: 18000,
      credit_token_balance: 0,
      redemption_rate_display: '1 Point = 1.0–1.5 cents',
      points_value_cents: 100,
      points_program_name: 'Chase Ultimate Rewards',
      card_description: 'The ideal no-annual-fee companion card. 1.5% base on everything with bonus categories. When paired with CSR or CSP, points pool and become worth 1.25–1.5¢ each toward travel.',
      pros: [
        'No annual fee',
        '1.5% base cashback on all purchases (above industry 1%)',
        '3% on dining and drugstores',
        '5% on Chase Travel portal',
        'Pairs with CSR/CSP to boost point value to 1.5¢',
        'No minimum redemption amount',
        '0% intro APR on purchases for 15 months',
      ],
      cons: [
        '3% foreign transaction fee',
        'Requires a premium Chase card to unlock best redemptions',
        'No travel benefits on its own',
      ],
      features: [
        '1.5% unlimited cashback on all purchases',
        '3% cashback on dining and drugstore purchases',
        '5% cashback via Chase Travel portal',
        '0% intro APR for 15 months on purchases and balance transfers',
        'No annual fee',
        'Pairs with CSR for 1.5¢/point travel redemptions',
        'Purchase protection (120 days)',
        'Extended warranty (1 extra year)',
      ],
      financials: {
        annual_fee: 0,
        foreign_transaction_fee_pct: 3,
        standard_apr: 0.1999,
        promos: {
          intro_purchase_apr: 0,
          intro_purchase_apr_expiration: new Date('2026-09-01'),
          balance_transfer_fee_pct: 3,
          intro_bt_apr: 0,
          intro_bt_apr_expiration: new Date('2026-09-01'),
        },
      },
      rewards_structure: {
        base_multiplier: 1.5,
        fixed_categories: [
          { category: 'dining', multiplier: 3, cap_amount_usd: null, cap_period: null, current_spend_towards_cap: 0, post_cap_multiplier: 1.5 },
          { category: 'restaurant', multiplier: 3, cap_amount_usd: null, cap_period: null, current_spend_towards_cap: 0, post_cap_multiplier: 1.5 },
          { category: 'drug', multiplier: 3, cap_amount_usd: null, cap_period: null, current_spend_towards_cap: 0, post_cap_multiplier: 1.5 },
          { category: 'pharmacy', multiplier: 3, cap_amount_usd: null, cap_period: null, current_spend_towards_cap: 0, post_cap_multiplier: 1.5 },
        ],
      },
      benefits_and_credits: {
        statement_credits: [],
        portal_bonuses: [
          { portal_name: 'Chase Travel', portal_url: 'https://travel.chase.com', categories: ['flights', 'hotel', 'rental car'], bonus_multiplier: 5, bonus_type: 'multiplier' as const },
        ],
        purchase_protections: {
          extended_warranty: true,
          purchase_protection_days: 120,
          return_protection_days: 0,
          cell_phone_protection: false,
          trip_cancellation: false,
          primary_rental_cdw: false,
        },
        transfer_partners: [],
        airline_perks: [],
        general_perks: ['No annual fee', '0% intro APR 15 months', 'No minimum redemption'],
      },
    },

    // ── 7. Amex Blue Cash Preferred ───────────────────────────────────────────
    {
      user_id: userId,
      card_id: 'card_amex_blue_cash_preferred_01',
      display_name: 'Amex Blue Cash Preferred',
      card_type: 'personal' as CardType,
      network: 'AMEX' as Network,
      currency_type: 'USD' as CurrencyType,
      current_balance_owed: 0,
      credit_limit: 18000,
      points_balance: 0,
      credit_token_balance: 38000,
      redemption_rate_display: '$1.00 = 100 OP',
      points_value_cents: 100,
      points_program_name: null,
      card_description: 'The #1 card for US supermarket spending. 6% cash back at US supermarkets (up to $6,000/year) and 6% on select US streaming services. A $95/year card that pays for itself after $1,600 of grocery spend.',
      pros: [
        '6% cash back at US supermarkets (best rate available)',
        '6% on select US streaming subscriptions',
        '3% on transit (Uber, Lyft, subway, parking)',
        '3% at US gas stations',
        '$84/year in streaming credits ($7/month Disney Bundle)',
        'Solid purchase protection',
        '0% intro APR for 12 months',
      ],
      cons: [
        '$95 annual fee (waived first year)',
        'Grocery bonus capped at $6,000/year (then 1%)',
        'No travel perks or lounge access',
        '2.7% foreign transaction fee',
        'Cashback as statement credit only',
      ],
      features: [
        '6% cash back at U.S. supermarkets (up to $6,000/year)',
        '6% on select U.S. streaming subscriptions',
        '3% at U.S. gas stations',
        '3% on transit (taxis, rideshare, parking, buses, trains)',
        '1% on all other purchases',
        '$84 Disney Bundle credit ($7/month)',
        '0% intro APR for 12 months on purchases',
        'Purchase protection and extended warranty',
        'Return protection (60 days, up to $300/item)',
      ],
      financials: {
        annual_fee: 95,
        foreign_transaction_fee_pct: 2.7,
        standard_apr: 0.1949,
        promos: {
          intro_purchase_apr: 0,
          intro_purchase_apr_expiration: new Date('2026-06-01'),
        },
      },
      rewards_structure: {
        base_multiplier: 1,
        fixed_categories: [
          { category: 'grocer', multiplier: 6, cap_amount_usd: 6000, cap_period: 'calendar_year', current_spend_towards_cap: 0, post_cap_multiplier: 1 },
          { category: 'streaming', multiplier: 6, cap_amount_usd: null, cap_period: null, current_spend_towards_cap: 0, post_cap_multiplier: 1 },
          { category: 'gas', multiplier: 3, cap_amount_usd: null, cap_period: null, current_spend_towards_cap: 0, post_cap_multiplier: 1 },
          { category: 'transit', multiplier: 3, cap_amount_usd: null, cap_period: null, current_spend_towards_cap: 0, post_cap_multiplier: 1 },
          { category: 'rideshare', multiplier: 3, cap_amount_usd: null, cap_period: null, current_spend_towards_cap: 0, post_cap_multiplier: 1 },
        ],
      },
      benefits_and_credits: {
        statement_credits: [
          { name: 'Disney Bundle Credit', amount_usd: 84, reset_period: 'calendar_year', amount_redeemed: 0, merchant_categories: ['streaming', 'entertainment'] },
        ],
        portal_bonuses: [],
        purchase_protections: {
          extended_warranty: true,
          purchase_protection_days: 90,
          return_protection_days: 60,
          cell_phone_protection: false,
          trip_cancellation: false,
          primary_rental_cdw: false,
        },
        transfer_partners: [],
        airline_perks: [],
        general_perks: ['Best-in-class grocery cashback rate', '0% intro APR 12 months'],
      },
    },

    // ── 8. Citi Double Cash ───────────────────────────────────────────────────
    {
      user_id: userId,
      card_id: 'card_citi_double_cash_01',
      display_name: 'Citi Double Cash',
      card_type: 'personal' as CardType,
      network: 'MASTERCARD' as Network,
      currency_type: 'USD' as CurrencyType,
      current_balance_owed: 0,
      credit_limit: 10000,
      points_balance: 0,
      credit_token_balance: 22000,
      redemption_rate_display: '$1.00 = 100 OP',
      points_value_cents: 100,
      points_program_name: null,
      card_description: 'The simplest high-value card in the market. 1% when you buy + 1% when you pay = 2% effective cashback on everything, forever, with no annual fee.',
      pros: [
        '2% effective cashback on everything — no categories',
        'No annual fee',
        'No rotating categories or caps to track',
        'Mastercard acceptance (broader than Amex/Discover)',
        'Balance transfer option with competitive promo rate',
        'Can convert cashback to Citi ThankYou Points if you have Premier',
      ],
      cons: [
        '3% foreign transaction fee',
        'No sign-up bonus historically',
        'No travel benefits or protections',
        'Cashback only via statement credit or check',
      ],
      features: [
        '2% cashback on all purchases (1% at purchase, 1% when paid)',
        'No annual fee',
        'No minimum redemption threshold',
        'Balance transfer promo available',
        'Cashback convertible to Citi ThankYou Points with eligible cards',
      ],
      financials: {
        annual_fee: 0,
        foreign_transaction_fee_pct: 3,
        standard_apr: 0.1899,
        promos: {
          balance_transfer_fee_pct: 5,
          intro_bt_apr: 0,
          intro_bt_apr_expiration: new Date('2026-09-01'),
        },
      },
      rewards_structure: {
        base_multiplier: 2,
        fixed_categories: [],
      },
      benefits_and_credits: {
        statement_credits: [],
        portal_bonuses: [],
        purchase_protections: {
          extended_warranty: false,
          purchase_protection_days: 0,
          return_protection_days: 0,
          cell_phone_protection: false,
          trip_cancellation: false,
          primary_rental_cdw: false,
        },
        transfer_partners: [],
        airline_perks: [],
        general_perks: ['No annual fee', '2% flat rate — zero category management'],
      },
    },

    // ── 9. Wells Fargo Active Cash ────────────────────────────────────────────
    {
      user_id: userId,
      card_id: 'card_wells_fargo_active_cash_01',
      display_name: 'Wells Fargo Active Cash',
      card_type: 'personal' as CardType,
      network: 'VISA' as Network,
      currency_type: 'USD' as CurrencyType,
      current_balance_owed: 0,
      credit_limit: 10000,
      points_balance: 0,
      credit_token_balance: 25000,
      redemption_rate_display: '$1.00 = 100 OP',
      points_value_cents: 100,
      points_program_name: null,
      card_description: 'The best no-annual-fee 2% card with cell phone protection. Pay your phone bill with this card and get up to $600 in phone protection with a $25 deductible.',
      pros: [
        'Unlimited 2% cash rewards on all purchases',
        'No annual fee',
        'Cell phone protection up to $600 (just pay phone bill with card)',
        'Visa acceptance (near-universal)',
        '0% intro APR on purchases + balance transfers for 15 months',
        '$200 cash rewards bonus after $500 spend in first 3 months',
      ],
      cons: [
        '3% foreign transaction fee',
        'No bonus categories to maximize',
        'No travel benefits',
        'Limited card benefits overall',
      ],
      features: [
        'Unlimited 2% cash rewards on all purchases',
        'Cell phone protection up to $600 ($25 deductible)',
        '$200 cash rewards sign-up bonus (after $500 spend, 3 months)',
        '0% intro APR for 15 months (purchases + balance transfers)',
        'No annual fee',
        'Visa Signature benefits',
      ],
      financials: {
        annual_fee: 0,
        foreign_transaction_fee_pct: 3,
        standard_apr: 0.1999,
        promos: {
          intro_purchase_apr: 0,
          intro_purchase_apr_expiration: new Date('2026-09-01'),
          balance_transfer_fee_pct: 3,
          intro_bt_apr: 0,
          intro_bt_apr_expiration: new Date('2026-09-01'),
        },
      },
      rewards_structure: {
        base_multiplier: 2,
        fixed_categories: [],
      },
      benefits_and_credits: {
        statement_credits: [],
        portal_bonuses: [],
        purchase_protections: {
          extended_warranty: false,
          purchase_protection_days: 90,
          return_protection_days: 0,
          cell_phone_protection: true,
          trip_cancellation: false,
          primary_rental_cdw: false,
        },
        transfer_partners: [],
        airline_perks: [],
        general_perks: ['No annual fee', 'Cell phone protection $600', '0% intro APR 15 months'],
      },
    },

    // ── 10. Discover it Cash Back ──────────────────────────────────────────────
    {
      user_id: userId,
      card_id: 'card_discover_it_cashback_01',
      display_name: 'Discover it Cash Back',
      card_type: 'personal' as CardType,
      network: 'DISCOVER' as Network,
      currency_type: 'USD' as CurrencyType,
      current_balance_owed: 0,
      credit_limit: 7000,
      points_balance: 0,
      credit_token_balance: 15000,
      redemption_rate_display: '$1.00 = 100 OP',
      points_value_cents: 100,
      points_program_name: null,
      card_description: 'The best first-year cashback card. 5% rotating categories (up to $1,500/quarter) automatically doubled via Cashback Match in year one — effectively 10% on the categories that matter.',
      pros: [
        '5% cashback on rotating quarterly categories (up to $1,500/quarter)',
        'Cashback Match doubles ALL cashback earned in year one',
        'No annual fee',
        'No foreign transaction fees (rare for a no-fee card)',
        'Free FICO credit score monitoring',
        '0% intro APR for 15 months',
        'Freeze/unfreeze card instantly in app',
      ],
      cons: [
        'Must remember to activate categories each quarter',
        'Discover acceptance lower than Visa/Mastercard internationally',
        'Only 1% base cashback outside bonus categories',
        '5% capped at $1,500/quarter then drops to 1%',
      ],
      features: [
        '5% cashback on rotating categories (Q1: grocery/drugstore, Q2: gas/EV, Q3: restaurants, Q4: Amazon/Target)',
        '1% cashback on all other purchases',
        'Cashback Match: Discover doubles all cashback earned in first 12 months',
        'No annual fee',
        'No foreign transaction fees',
        '0% intro APR for 15 months (purchases + balance transfers)',
        'Free FICO score + Social Security number alerts',
      ],
      financials: {
        annual_fee: 0,
        foreign_transaction_fee_pct: 0,
        standard_apr: 0.1699,
        promos: {
          intro_purchase_apr: 0,
          intro_purchase_apr_expiration: new Date('2026-09-01'),
          balance_transfer_fee_pct: 3,
          intro_bt_apr: 0,
          intro_bt_apr_expiration: new Date('2026-09-01'),
        },
      },
      rewards_structure: {
        base_multiplier: 1,
        fixed_categories: [
          { category: 'grocer', multiplier: 5, cap_amount_usd: 1500, cap_period: 'quarter', current_spend_towards_cap: 0, post_cap_multiplier: 1 },
          { category: 'drug', multiplier: 5, cap_amount_usd: 1500, cap_period: 'quarter', current_spend_towards_cap: 0, post_cap_multiplier: 1 },
          { category: 'restaurant', multiplier: 5, cap_amount_usd: 1500, cap_period: 'quarter', current_spend_towards_cap: 0, post_cap_multiplier: 1 },
          { category: 'gas', multiplier: 5, cap_amount_usd: 1500, cap_period: 'quarter', current_spend_towards_cap: 0, post_cap_multiplier: 1 },
        ],
        rotating_categories: {
          is_active: true,
          current_quarter: 'Q2 2025',
          active_categories: ['gas', 'ev charging', 'home improvement', 'select streaming'],
          multiplier: 5,
        },
      },
      benefits_and_credits: {
        statement_credits: [],
        portal_bonuses: [],
        purchase_protections: {
          extended_warranty: false,
          purchase_protection_days: 0,
          return_protection_days: 0,
          cell_phone_protection: false,
          trip_cancellation: false,
          primary_rental_cdw: false,
        },
        transfer_partners: [],
        airline_perks: [],
        general_perks: ['No annual fee', 'No foreign transaction fees', 'Cashback Match year one', 'Free FICO score'],
      },
    },

    // ── 11. Ink Business Preferred ────────────────────────────────────────────
    {
      user_id: userId,
      card_id: 'card_ink_preferred_01',
      display_name: 'Chase Ink Business Preferred',
      card_type: 'business' as CardType,
      network: 'VISA' as Network,
      currency_type: 'POINTS' as CurrencyType,
      current_balance_owed: 0,
      credit_limit: 25000,
      points_balance: 48000,
      credit_token_balance: 0,
      redemption_rate_display: '1 Point = 1.25 cents (Chase Travel)',
      points_value_cents: 125,
      points_program_name: 'Chase Ultimate Rewards',
      card_description: 'The best business card for travel and advertising spend. 3x on the first $150,000 in travel, shipping, advertising, and internet/cable/phone services annually.',
      pros: [
        '3x on travel, shipping, advertising, internet/cable/phone (up to $150k)',
        'Access to all 14 Chase Ultimate Rewards transfer partners',
        'Points pool with personal Chase cards',
        'Primary rental CDW for business rentals',
        'Cell phone protection up to $1,000',
        'Employee cards at no cost',
        'No foreign transaction fees',
      ],
      cons: [
        '$95 annual fee',
        'Bonus categories capped at $150,000/year combined',
        'Must have a business to qualify',
      ],
      features: [
        '3x points on travel, shipping, advertising, internet/cable/phone (first $150k/year)',
        '1x on all other purchases',
        'Employee cards at no additional cost',
        'Cell phone protection: up to $1,000 ($100 deductible)',
        'Primary rental CDW for business purposes',
        'Trip delay/cancellation insurance',
        'Transfer to 14+ airline and hotel partners',
        'No foreign transaction fees',
      ],
      financials: {
        annual_fee: 95,
        foreign_transaction_fee_pct: 0,
        standard_apr: 0.2074,
      },
      rewards_structure: {
        base_multiplier: 1,
        fixed_categories: [
          { category: 'travel', multiplier: 3, cap_amount_usd: 150000, cap_period: 'calendar_year', current_spend_towards_cap: 0, post_cap_multiplier: 1 },
          { category: 'shipping', multiplier: 3, cap_amount_usd: 150000, cap_period: 'calendar_year', current_spend_towards_cap: 0, post_cap_multiplier: 1 },
          { category: 'advertising', multiplier: 3, cap_amount_usd: 150000, cap_period: 'calendar_year', current_spend_towards_cap: 0, post_cap_multiplier: 1 },
          { category: 'internet', multiplier: 3, cap_amount_usd: 150000, cap_period: 'calendar_year', current_spend_towards_cap: 0, post_cap_multiplier: 1 },
          { category: 'telecom', multiplier: 3, cap_amount_usd: 150000, cap_period: 'calendar_year', current_spend_towards_cap: 0, post_cap_multiplier: 1 },
        ],
      },
      benefits_and_credits: {
        statement_credits: [],
        portal_bonuses: [
          { portal_name: 'Chase Travel', portal_url: 'https://travel.chase.com', categories: ['flights', 'hotel', 'rental car'], bonus_multiplier: 1.25, bonus_type: 'multiplier' as const },
        ],
        purchase_protections: {
          extended_warranty: true,
          purchase_protection_days: 120,
          return_protection_days: 90,
          cell_phone_protection: true,
          trip_cancellation: true,
          primary_rental_cdw: true,
        },
        transfer_partners: [
          { program: 'United MileagePlus', ratio: '1:1', cpp_min: 1.20, cpp_max: 2.10 },
          { program: 'Southwest Rapid Rewards', ratio: '1:1', cpp_min: 1.40, cpp_max: 1.70 },
          { program: 'British Airways Avios', ratio: '1:1', cpp_min: 1.40, cpp_max: 2.40 },
          { program: 'World of Hyatt', ratio: '1:1', cpp_min: 1.50, cpp_max: 2.30 },
          { program: 'Air France/KLM Flying Blue', ratio: '1:1', cpp_min: 1.30, cpp_max: 1.90 },
        ],
        airline_perks: ['Primary rental CDW (business)', 'Cell phone protection $1,000'],
        general_perks: ['No foreign transaction fees', 'Employee cards free', 'Points pool with personal cards'],
      },
    },

    // ── 12. Ink Business Cash ──────────────────────────────────────────────────
    {
      user_id: userId,
      card_id: 'card_ink_business_cash_01',
      display_name: 'Chase Ink Business Cash',
      card_type: 'business' as CardType,
      network: 'VISA' as Network,
      currency_type: 'POINTS' as CurrencyType,
      current_balance_owed: 0,
      credit_limit: 20000,
      points_balance: 31000,
      credit_token_balance: 0,
      redemption_rate_display: '1 Point = 1.0–1.5 cents',
      points_value_cents: 100,
      points_program_name: 'Chase Ultimate Rewards',
      card_description: 'The best no-annual-fee business card. 5% cashback at office supply stores and on internet/cable/phone services (up to $25k/year). Pools with Chase Sapphire for travel upgrades.',
      pros: [
        'No annual fee',
        '5% on office supply stores + internet/cable/phone (up to $25k)',
        '2% on gas stations and restaurants (up to $25k)',
        'Pools points with CSR/CSP to unlock 1.5¢/point value',
        'Employee cards at no cost',
        'Purchase protections included',
      ],
      cons: [
        'Bonus categories capped at $25,000/year each',
        '3% foreign transaction fee',
        'Requires a business to qualify',
        'Must have a premium Chase card to unlock best point value',
      ],
      features: [
        '5% cashback at office supply stores + internet/cable/phone (up to $25k/year)',
        '2% at gas stations and restaurants (up to $25k/year)',
        '1% on all other purchases',
        'No annual fee',
        'Employee cards at no cost',
        'Year-end spending summaries',
        'Purchase protection and extended warranty',
        'Pairs with CSR/CSP for 1.5¢/point travel value',
      ],
      financials: {
        annual_fee: 0,
        foreign_transaction_fee_pct: 3,
        standard_apr: 0.1874,
        promos: {
          intro_purchase_apr: 0,
          intro_purchase_apr_expiration: new Date('2026-09-01'),
        },
      },
      rewards_structure: {
        base_multiplier: 1,
        fixed_categories: [
          { category: 'office supply', multiplier: 5, cap_amount_usd: 25000, cap_period: 'calendar_year', current_spend_towards_cap: 0, post_cap_multiplier: 1 },
          { category: 'internet', multiplier: 5, cap_amount_usd: 25000, cap_period: 'calendar_year', current_spend_towards_cap: 0, post_cap_multiplier: 1 },
          { category: 'telecom', multiplier: 5, cap_amount_usd: 25000, cap_period: 'calendar_year', current_spend_towards_cap: 0, post_cap_multiplier: 1 },
          { category: 'gas', multiplier: 2, cap_amount_usd: 25000, cap_period: 'calendar_year', current_spend_towards_cap: 0, post_cap_multiplier: 1 },
          { category: 'restaurant', multiplier: 2, cap_amount_usd: 25000, cap_period: 'calendar_year', current_spend_towards_cap: 0, post_cap_multiplier: 1 },
        ],
      },
      benefits_and_credits: {
        statement_credits: [],
        portal_bonuses: [],
        purchase_protections: {
          extended_warranty: true,
          purchase_protection_days: 120,
          return_protection_days: 0,
          cell_phone_protection: false,
          trip_cancellation: false,
          primary_rental_cdw: false,
        },
        transfer_partners: [],
        airline_perks: [],
        general_perks: ['No annual fee', 'Employee cards free', 'Pools with premium Chase cards'],
      },
    },

    // ── 13. Capital One SavorOne ───────────────────────────────────────────────
    {
      user_id: userId,
      card_id: 'card_capital_one_savorone_01',
      display_name: 'Capital One SavorOne',
      card_type: 'personal' as CardType,
      network: 'MASTERCARD' as Network,
      currency_type: 'USD' as CurrencyType,
      current_balance_owed: 0,
      credit_limit: 8000,
      points_balance: 0,
      credit_token_balance: 19000,
      redemption_rate_display: '$1.00 = 100 OP',
      points_value_cents: 100,
      points_program_name: null,
      card_description: 'The best no-annual-fee dining and entertainment card. 3% on dining, entertainment, popular streaming, and grocery stores. Perfect complement to a travel rewards card.',
      pros: [
        'No annual fee',
        '3% on dining, entertainment, popular streaming, and grocery stores',
        '5% on hotels and rental cars booked via Capital One Travel',
        '8% on Capital One Entertainment purchases',
        'No foreign transaction fees',
        '0% intro APR for 15 months',
      ],
      cons: [
        'Mastercard (slightly less accepted internationally than Visa)',
        'No travel benefits or lounge access',
        'Grocery bonus excludes Walmart and Target',
      ],
      features: [
        '3% cashback on dining, entertainment, popular streaming, grocery stores',
        '5% on hotels and rental cars via Capital One Travel',
        '8% on Capital One Entertainment',
        '1.5% on all other purchases',
        'No annual fee',
        'No foreign transaction fees',
        '0% intro APR for 15 months',
      ],
      financials: {
        annual_fee: 0,
        foreign_transaction_fee_pct: 0,
        standard_apr: 0.1999,
        promos: {
          intro_purchase_apr: 0,
          intro_purchase_apr_expiration: new Date('2026-09-01'),
        },
      },
      rewards_structure: {
        base_multiplier: 1.5,
        fixed_categories: [
          { category: 'dining', multiplier: 3, cap_amount_usd: null, cap_period: null, current_spend_towards_cap: 0, post_cap_multiplier: 1.5 },
          { category: 'restaurant', multiplier: 3, cap_amount_usd: null, cap_period: null, current_spend_towards_cap: 0, post_cap_multiplier: 1.5 },
          { category: 'entertainment', multiplier: 3, cap_amount_usd: null, cap_period: null, current_spend_towards_cap: 0, post_cap_multiplier: 1.5 },
          { category: 'streaming', multiplier: 3, cap_amount_usd: null, cap_period: null, current_spend_towards_cap: 0, post_cap_multiplier: 1.5 },
          { category: 'grocer', multiplier: 3, cap_amount_usd: null, cap_period: null, current_spend_towards_cap: 0, post_cap_multiplier: 1.5 },
          { category: 'hotel', multiplier: 5, cap_amount_usd: null, cap_period: null, current_spend_towards_cap: 0, post_cap_multiplier: 1.5 },
          { category: 'rental car', multiplier: 5, cap_amount_usd: null, cap_period: null, current_spend_towards_cap: 0, post_cap_multiplier: 1.5 },
        ],
      },
      benefits_and_credits: {
        statement_credits: [],
        portal_bonuses: [],
        purchase_protections: {
          extended_warranty: false,
          purchase_protection_days: 0,
          return_protection_days: 0,
          cell_phone_protection: false,
          trip_cancellation: false,
          primary_rental_cdw: false,
        },
        transfer_partners: [],
        airline_perks: [],
        general_perks: ['No annual fee', 'No foreign transaction fees', '0% intro APR 15 months'],
      },
    },

    // ── 14. Citi Premier ──────────────────────────────────────────────────────
    {
      user_id: userId,
      card_id: 'card_citi_premier_01',
      display_name: 'Citi Premier',
      card_type: 'personal' as CardType,
      network: 'MASTERCARD' as Network,
      currency_type: 'POINTS' as CurrencyType,
      current_balance_owed: 0,
      credit_limit: 12000,
      points_balance: 35000,
      credit_token_balance: 0,
      redemption_rate_display: '1 ThankYou Point = 1.0–1.7 cents',
      points_value_cents: 130,
      points_program_name: 'Citi ThankYou Rewards',
      card_description: 'Best-in-class 3x breadth: air, hotels, groceries, restaurants, AND gas — no other $95 card covers all five at 3x. Access to 17 airline partners including Turkish, Flying Blue, and Avianca.',
      pros: [
        '3x on air, hotels, groceries, restaurants, and gas stations',
        '10x on hotels, car rentals, attractions via Citi Travel (through 2025)',
        '$100 annual hotel savings benefit',
        'Transfer to 17 airline partners — some with very high CPP (Turkish, Flying Blue)',
        'No foreign transaction fees',
      ],
      cons: [
        '$95 annual fee',
        'No lounge access',
        'No travel protections (trip delay, CDW)',
        'ThankYou Points ecosystem less known than Chase/Amex',
      ],
      features: [
        '3x on air travel, hotels, groceries, restaurants, gas stations',
        '10x on hotels, car rentals, attractions via Citi Travel (through Dec 2025)',
        '1x on all other purchases',
        '$100 annual hotel savings benefit (single hotel stay of $500+)',
        'Transfer to 17 airline partners',
        'No foreign transaction fees',
      ],
      financials: {
        annual_fee: 95,
        foreign_transaction_fee_pct: 0,
        standard_apr: 0.2099,
      },
      rewards_structure: {
        base_multiplier: 1,
        fixed_categories: [
          { category: 'flights', multiplier: 3, cap_amount_usd: null, cap_period: null, current_spend_towards_cap: 0, post_cap_multiplier: 1 },
          { category: 'hotel', multiplier: 3, cap_amount_usd: null, cap_period: null, current_spend_towards_cap: 0, post_cap_multiplier: 1 },
          { category: 'grocer', multiplier: 3, cap_amount_usd: null, cap_period: null, current_spend_towards_cap: 0, post_cap_multiplier: 1 },
          { category: 'dining', multiplier: 3, cap_amount_usd: null, cap_period: null, current_spend_towards_cap: 0, post_cap_multiplier: 1 },
          { category: 'gas', multiplier: 3, cap_amount_usd: null, cap_period: null, current_spend_towards_cap: 0, post_cap_multiplier: 1 },
        ],
      },
      benefits_and_credits: {
        statement_credits: [
          { name: 'Hotel Savings Benefit', amount_usd: 100, reset_period: 'calendar_year', amount_redeemed: 0, merchant_categories: ['hotel'] },
        ],
        portal_bonuses: [
          { portal_name: 'Citi Travel', portal_url: 'https://travel.citi.com', categories: ['hotel', 'rental car', 'activities'], bonus_multiplier: 10, bonus_type: 'multiplier' as const },
        ],
        purchase_protections: {
          extended_warranty: false,
          purchase_protection_days: 0,
          return_protection_days: 0,
          cell_phone_protection: false,
          trip_cancellation: false,
          primary_rental_cdw: false,
        },
        transfer_partners: [
          { program: 'Turkish Airlines Miles&Smiles', ratio: '1:1', cpp_min: 1.40, cpp_max: 3.50 },
          { program: 'Air France/KLM Flying Blue', ratio: '1:1', cpp_min: 1.30, cpp_max: 1.90 },
          { program: 'Avianca LifeMiles', ratio: '1:1', cpp_min: 1.30, cpp_max: 1.80 },
          { program: 'Emirates Skywards', ratio: '1:1', cpp_min: 1.30, cpp_max: 1.70 },
          { program: 'Etihad Guest', ratio: '1:1', cpp_min: 1.20, cpp_max: 1.60 },
          { program: 'Singapore Airlines KrisFlyer', ratio: '1:1', cpp_min: 1.50, cpp_max: 2.20 },
          { program: 'Virgin Atlantic Flying Club', ratio: '1:1', cpp_min: 1.40, cpp_max: 2.00 },
        ],
        airline_perks: [],
        general_perks: ['No foreign transaction fees', 'Hotel savings benefit $100/year'],
      },
    },

    // ── 15. United Explorer ────────────────────────────────────────────────────
    {
      user_id: userId,
      card_id: 'card_united_explorer_01',
      display_name: 'United Explorer Card',
      card_type: 'personal' as CardType,
      network: 'VISA' as Network,
      currency_type: 'MILES' as CurrencyType,
      current_balance_owed: 0,
      credit_limit: 14000,
      points_balance: 42000,
      credit_token_balance: 0,
      redemption_rate_display: '1 Mile = 1.0–2.0+ cents',
      points_value_cents: 140,
      points_program_name: 'United MileagePlus',
      card_description: 'The best co-branded airline card for United loyalists. Free first checked bag for you + 1 companion (saves $140/round-trip). 2 United Club one-time passes per year. 25% back on in-flight purchases.',
      pros: [
        'Free first checked bag (cardholder + 1 companion)',
        '2 United Club one-time passes per year ($59 value each)',
        '2x miles on United purchases, dining, and hotels',
        'Priority boarding (Zone 2)',
        '25% back on United in-flight purchases',
        '$100 Global Entry / TSA PreCheck credit',
        'No foreign transaction fees',
        'United miles transfer to Star Alliance partners',
      ],
      cons: [
        '$95 annual fee (waived first year)',
        'Only valuable if you fly United regularly',
        'Free bag benefit requires booking with card',
        'Miles value highly variable — 1–4¢/mile depending on redemption',
      ],
      features: [
        '2x miles on United purchases',
        '2x miles on dining and hotel stays',
        '1x miles on all other purchases',
        'Free first checked bag for cardholder + 1 companion per flight',
        '2 United Club one-time passes per year',
        'Priority boarding (Zone 2)',
        '25% statement credit on United in-flight food, beverages, Wi-Fi',
        '$100 Global Entry or TSA PreCheck credit every 4 years',
        'No foreign transaction fees',
      ],
      financials: {
        annual_fee: 95,
        foreign_transaction_fee_pct: 0,
        standard_apr: 0.2174,
      },
      rewards_structure: {
        base_multiplier: 1,
        fixed_categories: [
          { category: 'flights', multiplier: 2, cap_amount_usd: null, cap_period: null, current_spend_towards_cap: 0, post_cap_multiplier: 1 },
          { category: 'dining', multiplier: 2, cap_amount_usd: null, cap_period: null, current_spend_towards_cap: 0, post_cap_multiplier: 1 },
          { category: 'hotel', multiplier: 2, cap_amount_usd: null, cap_period: null, current_spend_towards_cap: 0, post_cap_multiplier: 1 },
        ],
      },
      benefits_and_credits: {
        statement_credits: [
          { name: 'In-flight Purchase Credit', amount_usd: 0, reset_period: 'per_statement', amount_redeemed: 0, merchant_categories: ['airline', 'in-flight'] },
        ],
        portal_bonuses: [],
        purchase_protections: {
          extended_warranty: true,
          purchase_protection_days: 90,
          return_protection_days: 0,
          cell_phone_protection: false,
          trip_cancellation: true,
          primary_rental_cdw: false,
        },
        transfer_partners: [
          { program: 'United MileagePlus', ratio: '1:1', cpp_min: 1.20, cpp_max: 2.10 },
          { program: 'Air Canada Aeroplan', ratio: '1:1', cpp_min: 1.40, cpp_max: 2.20 },
          { program: 'Lufthansa Miles & More', ratio: '1:1', cpp_min: 1.40, cpp_max: 1.90 },
          { program: 'ANA Mileage Club', ratio: '1:1', cpp_min: 1.60, cpp_max: 2.80 },
          { program: 'Singapore Airlines KrisFlyer', ratio: '1:1', cpp_min: 1.50, cpp_max: 2.20 },
        ],
        airline_perks: [
          'Free first checked bag (cardholder + companion)',
          '2 United Club one-time passes per year',
          'Priority boarding Zone 2',
          '25% back on in-flight purchases',
          'Global Entry credit ($100)',
        ],
        general_perks: ['No foreign transaction fees', 'Premier Access travel services'],
      },
    },

    // ── 16. Southwest Rapid Rewards Plus ──────────────────────────────────────
    {
      user_id: userId,
      card_id: 'card_southwest_plus_01',
      display_name: 'Southwest Rapid Rewards Plus',
      card_type: 'personal' as CardType,
      network: 'VISA' as Network,
      currency_type: 'POINTS' as CurrencyType,
      current_balance_owed: 0,
      credit_limit: 11000,
      points_balance: 33000,
      credit_token_balance: 0,
      redemption_rate_display: '1 Point = 1.4–1.7 cents',
      points_value_cents: 145,
      points_program_name: 'Southwest Rapid Rewards',
      card_description: 'Entry card to the Southwest ecosystem and Companion Pass path. 3,000 anniversary points worth ~$42. All points earned count toward the 135,000-point Companion Pass threshold.',
      pros: [
        '3,000 anniversary bonus points every year',
        '2x points on Southwest purchases, hotel, and car rental partners',
        'All points count toward Companion Pass',
        'No blackout dates or seat restrictions',
        'Points never expire while account is open',
        'No foreign transaction fees',
        '2 EarlyBird Check-Ins per year ($25 value each)',
      ],
      cons: [
        '$69 annual fee',
        'Only valuable for Southwest flyers',
        'Lower sign-up bonus than mid-tier cards',
        'No lounge access',
      ],
      features: [
        '3x points on Southwest purchases',
        '2x points on Rapid Rewards hotel and car rental partners',
        '2x points on local transit and commuting',
        '1x points on all other purchases',
        '3,000 anniversary points every card anniversary',
        '2 EarlyBird Check-In credits per year',
        'No blackout dates, no seat restrictions',
        'No foreign transaction fees',
      ],
      financials: {
        annual_fee: 69,
        foreign_transaction_fee_pct: 0,
        standard_apr: 0.2074,
      },
      rewards_structure: {
        base_multiplier: 1,
        fixed_categories: [
          { category: 'flights', multiplier: 3, cap_amount_usd: null, cap_period: null, current_spend_towards_cap: 0, post_cap_multiplier: 1 },
          { category: 'hotel', multiplier: 2, cap_amount_usd: null, cap_period: null, current_spend_towards_cap: 0, post_cap_multiplier: 1 },
          { category: 'rental car', multiplier: 2, cap_amount_usd: null, cap_period: null, current_spend_towards_cap: 0, post_cap_multiplier: 1 },
          { category: 'transit', multiplier: 2, cap_amount_usd: null, cap_period: null, current_spend_towards_cap: 0, post_cap_multiplier: 1 },
          { category: 'rideshare', multiplier: 2, cap_amount_usd: null, cap_period: null, current_spend_towards_cap: 0, post_cap_multiplier: 1 },
        ],
      },
      benefits_and_credits: {
        statement_credits: [],
        portal_bonuses: [],
        purchase_protections: {
          extended_warranty: false,
          purchase_protection_days: 90,
          return_protection_days: 0,
          cell_phone_protection: false,
          trip_cancellation: true,
          primary_rental_cdw: false,
        },
        transfer_partners: [
          { program: 'Southwest Rapid Rewards', ratio: '1:1', cpp_min: 1.40, cpp_max: 1.70 },
        ],
        airline_perks: ['2 EarlyBird Check-Ins per year', 'Points count toward Companion Pass'],
        general_perks: ['No foreign transaction fees', 'No blackout dates'],
      },
    },

    // ── 17. Amex Blue Cash Everyday ────────────────────────────────────────────
    {
      user_id: userId,
      card_id: 'card_amex_blue_cash_everyday_01',
      display_name: 'Amex Blue Cash Everyday',
      card_type: 'personal' as CardType,
      network: 'AMEX' as Network,
      currency_type: 'USD' as CurrencyType,
      current_balance_owed: 0,
      credit_limit: 12000,
      points_balance: 0,
      credit_token_balance: 16000,
      redemption_rate_display: '$1.00 = 100 OP',
      points_value_cents: 100,
      points_program_name: null,
      card_description: 'The no-fee sibling of Blue Cash Preferred. 3% at US supermarkets, US online retailers (including Amazon), and US gas stations. Ideal for light spenders who want grocery rewards without an annual fee.',
      pros: [
        'No annual fee',
        '3% at US supermarkets (up to $6,000/year)',
        '3% at US online retailers including Amazon (up to $6,000/year)',
        '3% at US gas stations (up to $6,000/year)',
        '$84/year in streaming credits ($7/month Disney Bundle)',
        '0% intro APR for 15 months',
      ],
      cons: [
        'All three 3% categories capped at $6,000/year each (then 1%)',
        '2.7% foreign transaction fee',
        'Amex acceptance lower at some merchants',
        'Cashback as statement credit only',
      ],
      features: [
        '3% at U.S. supermarkets (up to $6,000/year)',
        '3% at U.S. online retailers (up to $6,000/year) — includes Amazon',
        '3% at U.S. gas stations (up to $6,000/year)',
        '1% on all other eligible purchases',
        '$84 Disney Bundle credit ($7/month)',
        '0% intro APR for 15 months',
        'No annual fee',
        'Amex Offers access',
      ],
      financials: {
        annual_fee: 0,
        foreign_transaction_fee_pct: 2.7,
        standard_apr: 0.1899,
        promos: {
          intro_purchase_apr: 0,
          intro_purchase_apr_expiration: new Date('2026-09-01'),
        },
      },
      rewards_structure: {
        base_multiplier: 1,
        fixed_categories: [
          { category: 'grocer', multiplier: 3, cap_amount_usd: 6000, cap_period: 'calendar_year', current_spend_towards_cap: 0, post_cap_multiplier: 1 },
          { category: 'shopping', multiplier: 3, cap_amount_usd: 6000, cap_period: 'calendar_year', current_spend_towards_cap: 0, post_cap_multiplier: 1 },
          { category: 'electronics', multiplier: 3, cap_amount_usd: 6000, cap_period: 'calendar_year', current_spend_towards_cap: 0, post_cap_multiplier: 1 },
          { category: 'gas', multiplier: 3, cap_amount_usd: 6000, cap_period: 'calendar_year', current_spend_towards_cap: 0, post_cap_multiplier: 1 },
        ],
      },
      benefits_and_credits: {
        statement_credits: [
          { name: 'Disney Bundle Credit', amount_usd: 84, reset_period: 'calendar_year', amount_redeemed: 0, merchant_categories: ['streaming'] },
        ],
        portal_bonuses: [],
        purchase_protections: {
          extended_warranty: false,
          purchase_protection_days: 0,
          return_protection_days: 0,
          cell_phone_protection: false,
          trip_cancellation: false,
          primary_rental_cdw: false,
        },
        transfer_partners: [],
        airline_perks: [],
        general_perks: ['No annual fee', '3% on online shopping including Amazon', '0% intro APR 15 months'],
      },
    },

    // ── 18. Bank of America Premium Rewards ───────────────────────────────────
    {
      user_id: userId,
      card_id: 'card_bofa_premium_rewards_01',
      display_name: 'BofA Premium Rewards',
      card_type: 'personal' as CardType,
      network: 'VISA' as Network,
      currency_type: 'POINTS' as CurrencyType,
      current_balance_owed: 0,
      credit_limit: 20000,
      points_balance: 29000,
      credit_token_balance: 0,
      redemption_rate_display: '1 Point = 1.0 cent (up to 1.75¢ with Preferred Rewards)',
      points_value_cents: 150,
      points_program_name: 'Bank of America Rewards',
      card_description: 'The best card for BofA Preferred Rewards customers. Platinum Honors tier (≥$100k in BofA/Merrill assets) boosts all rewards by 75% — making this an effective 3.5% on travel/dining and 2.625% everywhere else.',
      pros: [
        'Up to 75% rewards bonus for Preferred Rewards Platinum Honors ($100k assets)',
        '2x points on travel and dining (becomes 3.5x at Platinum Honors)',
        '1.5x on everything else (becomes 2.625x at Platinum Honors)',
        '$100 airline incidental credit per year',
        '$100 TSA PreCheck/Global Entry credit',
        'No foreign transaction fees',
      ],
      cons: [
        '$95 annual fee',
        'Maximum value requires $100k+ in BofA/Merrill accounts',
        'Points only via BofA ecosytem — no transfer partners',
        'No lounge access',
      ],
      features: [
        '2x points on travel and dining',
        '1.5x on all other purchases',
        'Rewards bonus: 25% (Gold), 50% (Platinum), 75% (Platinum Honors)',
        '$100 airline incidental fee credit per year',
        '$100 Global Entry or TSA PreCheck credit',
        'No foreign transaction fees',
        'Travel and purchase protection benefits',
      ],
      financials: {
        annual_fee: 95,
        foreign_transaction_fee_pct: 0,
        standard_apr: 0.2074,
      },
      rewards_structure: {
        base_multiplier: 1.5,
        fixed_categories: [
          { category: 'travel', multiplier: 2, cap_amount_usd: null, cap_period: null, current_spend_towards_cap: 0, post_cap_multiplier: 1.5 },
          { category: 'flights', multiplier: 2, cap_amount_usd: null, cap_period: null, current_spend_towards_cap: 0, post_cap_multiplier: 1.5 },
          { category: 'hotel', multiplier: 2, cap_amount_usd: null, cap_period: null, current_spend_towards_cap: 0, post_cap_multiplier: 1.5 },
          { category: 'dining', multiplier: 2, cap_amount_usd: null, cap_period: null, current_spend_towards_cap: 0, post_cap_multiplier: 1.5 },
        ],
      },
      benefits_and_credits: {
        statement_credits: [
          { name: 'Airline Incidental Credit', amount_usd: 100, reset_period: 'calendar_year', amount_redeemed: 0, merchant_categories: ['flights', 'airline'] },
          { name: 'Global Entry/TSA PreCheck', amount_usd: 100, reset_period: 'every_4_years', amount_redeemed: 0, merchant_categories: ['travel'] },
        ],
        portal_bonuses: [],
        purchase_protections: {
          extended_warranty: true,
          purchase_protection_days: 90,
          return_protection_days: 0,
          cell_phone_protection: false,
          trip_cancellation: true,
          primary_rental_cdw: false,
        },
        transfer_partners: [],
        airline_perks: ['Global Entry/TSA PreCheck credit'],
        general_perks: ['No foreign transaction fees', 'Up to 75% rewards bonus with Preferred Rewards', '$100 airline incidental credit'],
      },
    },

    // ── 19. Discover it Student Cash Back ─────────────────────────────────────
    {
      user_id: userId,
      card_id: 'card_discover_it_student_01',
      display_name: 'Discover it Student Cash Back',
      card_type: 'personal' as CardType,
      network: 'DISCOVER' as Network,
      currency_type: 'USD' as CurrencyType,
      current_balance_owed: 0,
      credit_limit: 3000,
      points_balance: 0,
      credit_token_balance: 8500,
      redemption_rate_display: '$1.00 = 100 OP',
      points_value_cents: 100,
      points_program_name: null,
      card_description: 'The best starter card for students with no credit history. Same 5% rotating categories and Cashback Match as the regular Discover it, plus a $20 Good Grades reward. Helps build credit safely.',
      pros: [
        'Accepts applicants with no credit history',
        '5% on rotating categories (same as adult card)',
        'Cashback Match doubles all rewards in year one',
        '$20 Good Grades Reward (3.0+ GPA)',
        'No annual fee',
        'No foreign transaction fees',
        'Free FICO credit score',
        'No penalty APR for late payment (first late fee waived)',
      ],
      cons: [
        'Low initial credit limit ($500–$3,000)',
        'Discover acceptance lower internationally',
        'Higher APR than prime cards',
        'Must remember to activate categories quarterly',
      ],
      features: [
        '5% cashback on rotating quarterly categories (up to $1,500/quarter)',
        '1% on all other purchases',
        'Cashback Match in first year',
        '$20 Good Grades Reward (one per school year, 3.0 GPA minimum)',
        'No annual fee',
        'No foreign transaction fees',
        'Free FICO credit score',
        'First late fee waived, no penalty APR',
        '0% intro APR for 6 months on purchases',
      ],
      financials: {
        annual_fee: 0,
        foreign_transaction_fee_pct: 0,
        standard_apr: 0.1799,
        promos: {
          intro_purchase_apr: 0,
          intro_purchase_apr_expiration: new Date('2025-12-01'),
        },
      },
      rewards_structure: {
        base_multiplier: 1,
        fixed_categories: [
          { category: 'restaurant', multiplier: 5, cap_amount_usd: 1500, cap_period: 'quarter', current_spend_towards_cap: 0, post_cap_multiplier: 1 },
          { category: 'gas', multiplier: 5, cap_amount_usd: 1500, cap_period: 'quarter', current_spend_towards_cap: 0, post_cap_multiplier: 1 },
          { category: 'grocer', multiplier: 5, cap_amount_usd: 1500, cap_period: 'quarter', current_spend_towards_cap: 0, post_cap_multiplier: 1 },
        ],
        rotating_categories: {
          is_active: true,
          current_quarter: 'Q2 2025',
          active_categories: ['gas', 'ev charging', 'home improvement', 'select streaming'],
          multiplier: 5,
        },
      },
      benefits_and_credits: {
        statement_credits: [
          { name: 'Good Grades Reward', amount_usd: 20, reset_period: 'annual', amount_redeemed: 0, merchant_categories: [] },
        ],
        portal_bonuses: [],
        purchase_protections: {
          extended_warranty: false,
          purchase_protection_days: 0,
          return_protection_days: 0,
          cell_phone_protection: false,
          trip_cancellation: false,
          primary_rental_cdw: false,
        },
        transfer_partners: [],
        airline_perks: [],
        general_perks: ['No annual fee', 'No foreign transaction fees', 'First late fee waived', 'Cashback Match year one', 'Free FICO score'],
      },
    },

    // ── 20. Wells Fargo Reflect ────────────────────────────────────────────────
    {
      user_id: userId,
      card_id: 'card_wells_fargo_reflect_01',
      display_name: 'Wells Fargo Reflect',
      card_type: 'personal' as CardType,
      network: 'VISA' as Network,
      currency_type: 'USD' as CurrencyType,
      current_balance_owed: 4200,
      credit_limit: 15000,
      points_balance: 0,
      credit_token_balance: 0,
      redemption_rate_display: 'No rewards — optimized for 0% APR period',
      points_value_cents: 0,
      points_program_name: null,
      card_description: 'The longest 0% intro APR card available. 21 months of 0% APR on purchases and qualifying balance transfers. No rewards — but saves hundreds or thousands in interest while paying off existing balances.',
      pros: [
        'Up to 21 months 0% intro APR (18 months + 3 months if minimum payments made)',
        '0% applies to both purchases AND balance transfers',
        'No annual fee',
        'Cell phone protection up to $600 (pay phone bill with card)',
        'Visa Signature acceptance',
        'My Wells Fargo Deals cashback offers',
      ],
      cons: [
        'No ongoing rewards after intro period',
        '3% foreign transaction fee',
        '5% balance transfer fee (min $5)',
        'Rate jumps to standard APR after intro period',
      ],
      features: [
        '0% intro APR for up to 21 months (18 months + 3 month extension)',
        'Applies to purchases and qualifying balance transfers',
        'No annual fee',
        'Cell phone protection up to $600 ($25 deductible)',
        'Visa Signature benefits',
        'My Wells Fargo Deals: earn cashback at select merchants',
        'Balance transfer fee: 3% (first 120 days), then 5%',
      ],
      financials: {
        annual_fee: 0,
        foreign_transaction_fee_pct: 3,
        standard_apr: 0.1799,
        promos: {
          intro_purchase_apr: 0,
          intro_purchase_apr_expiration: new Date('2027-01-01'),
          balance_transfer_fee_pct: 3,
          intro_bt_apr: 0,
          intro_bt_apr_expiration: new Date('2027-01-01'),
        },
      },
      rewards_structure: {
        base_multiplier: 0,
        fixed_categories: [],
      },
      benefits_and_credits: {
        statement_credits: [],
        portal_bonuses: [],
        purchase_protections: {
          extended_warranty: false,
          purchase_protection_days: 0,
          return_protection_days: 0,
          cell_phone_protection: true,
          trip_cancellation: false,
          primary_rental_cdw: false,
        },
        transfer_partners: [],
        airline_perks: [],
        general_perks: ['No annual fee', '0% APR up to 21 months', 'Cell phone protection $600', 'Best balance transfer card available'],
      },
    },

  ];
}

export async function POST(request: Request) {
  try {
    const { email } = await request.json();
    
    if (!email) {
      return NextResponse.json({ error: 'Email required' }, { status: 400 });
    }

    await connectDB();
    
    const user = await User.findOne({ email });
    if (!user) {
      return NextResponse.json({ error: 'User not found' }, { status: 404 });
    }

    const userId = user._id.toString();
    
    // Delete existing cards
    await FiatCard.deleteMany({ user_id: userId });
    
    // Seed new cards
    const cards = buildCards(userId);
    await FiatCard.insertMany(cards);
    
    return NextResponse.json({ 
      message: 'Cards seeded successfully',
      userId,
      cardCount: cards.length 
    });
  } catch (error) {
    console.error('Seed error:', error);
    return NextResponse.json({ error: 'Failed to seed cards' }, { status: 500 });
  }
}
